# Generated by Django 4.2.5 on 2023-09-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="power_reactor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ReportDt", models.DateTimeField(verbose_name="Report datetime")),
                ("Unit", models.CharField(max_length=200)),
                ("Power", models.IntegerField(default=0)),
            ],
        ),
    ]
