# Generated by Django 4.2.5 on 2023-09-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("us_nrc", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="reactor_report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("PlantName_DocketNumber", models.CharField(max_length=500)),
                ("LicenseNumber", models.CharField(max_length=200)),
                ("ReactorType", models.CharField(max_length=200)),
                ("Location", models.CharField(max_length=500)),
                ("Owner", models.TextField(max_length=200)),
                ("NRC_Region", models.IntegerField(default=0)),
            ],
        ),
    ]
