# Generated by Django 4.2.5 on 2023-09-22 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("us_nrc", "0003_reactor_units_unit_report_delete_power_reactor_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="reactor_unit",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("PlantName_DocketNumber", models.CharField(max_length=500)),
                ("LicenseNumber", models.CharField(max_length=200)),
                ("ReactorType", models.CharField(max_length=200)),
                ("Location", models.CharField(max_length=500)),
                ("Owner", models.TextField(max_length=200)),
                ("NRC_Region", models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(name="reactor_units",),
    ]
