# Generated by Django 4.2.5 on 2023-09-22 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("us_nrc", "0004_reactor_unit_delete_reactor_units"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reactor_unit",
            old_name="PlantName_DocketNumber",
            new_name="PlantName",
        ),
        migrations.AddField(
            model_name="reactor_unit",
            name="DocketNumber",
            field=models.IntegerField(default=0),
        ),
    ]
