# Generated by Django 4.2.5 on 2023-09-22 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "us_nrc",
            "0005_rename_plantname_docketnumber_reactor_unit_plantname_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="reactor_unit",
            name="Owner",
            field=models.CharField(max_length=200),
        ),
    ]
