# Generated by Django 4.2.5 on 2023-09-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("us_nrc", "0006_alter_reactor_unit_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="fact_table",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("reactor_id", models.IntegerField(default=0)),
                ("report_id", models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name="unit_report",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
