# Generated by Django 4.2.5 on 2023-09-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("us_nrc", "0007_fact_table_alter_unit_report_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unit_report",
            name="ReportDt",
            field=models.CharField(max_length=300),
        ),
    ]
