# Generated by Django 4.2.5 on 2023-09-24 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("us_nrc", "0009_reactor_unit_state"),
    ]

    operations = [
        migrations.DeleteModel(name="fact_table",),
    ]
