# Generated by Django 4.2.5 on 2023-09-25 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("us_nrc", "0010_delete_fact_table"),
    ]

    operations = [
        migrations.RemoveField(model_name="reactor_unit", name="id",),
        migrations.AlterField(
            model_name="reactor_unit",
            name="PlantName",
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="unit_report",
            name="Unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="us_nrc.reactor_unit"
            ),
        ),
        migrations.AlterField(
            model_name="unit_report",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
