# Generated by Django 4.2.5 on 2023-09-25 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("us_nrc", "0011_remove_reactor_unit_id_alter_reactor_unit_plantname_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reactor_unit",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="reactor_unit",
            name="PlantName",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="unit_report",
            name="Unit",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="unit_report",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
