# Generated by Django 4.2.5 on 2023-09-26 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("us_nrc", "0013_alter_reactor_unit_plantname"),
    ]

    operations = [
        migrations.RenameModel(old_name="unit_report", new_name="report",),
    ]
