# Generated by Django 4.2.5 on 2023-09-26 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("us_nrc", "0014_rename_unit_report_report"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report_data",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("ReportDt", models.CharField(max_length=300)),
                ("Unit", models.CharField(max_length=200)),
                ("Power", models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(name="report",),
    ]
