# Generated by Django 4.2.5 on 2023-09-26 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("us_nrc", "0015_report_data_delete_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="report_data",
            name="reactor_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="us_nrc.reactor_unit",
            ),
        ),
    ]
