# Generated by Django 4.2.5 on 2023-09-26 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("us_nrc", "0016_report_data_reactor_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report_data",
            name="reactor_id",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
