# Generated by Django 4.2.5 on 2023-09-26 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("us_nrc", "0018_alter_report_data_reactor_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report_data",
            name="reactor_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="us_nrc.reactor_unit",
            ),
            preserve_default=False,
        ),
    ]
