# Generated by Django 4.2.5 on 2023-09-26 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("us_nrc", "0019_alter_report_data_reactor_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report_data",
            name="reactor_id",
            field=models.IntegerField(default=0),
        ),
    ]
