# Generated by Django 4.2.5 on 2023-09-26 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("us_nrc", "0020_alter_report_data_reactor_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="report_data", old_name="reactor_id", new_name="reactor",
        ),
    ]
