# Generated by Django 4.2.5 on 2023-09-27 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("us_nrc", "0021_rename_reactor_id_report_data_reactor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report_data",
            name="reactor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="us_nrc.reactor_unit",
            ),
        ),
    ]
