# Generated by Django 4.2.5 on 2023-09-29 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("us_nrc", "0023_report_data_reportperiod_report_data_reporttime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report_data", name="ReportDt", field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="report_data",
            name="reactor",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="us_nrc.reactor_unit",
            ),
            preserve_default=False,
        ),
    ]
