# Generated by Django 4.2.5 on 2023-09-29 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("us_nrc", "0024_alter_report_data_reportdt_alter_report_data_reactor"),
    ]

    operations = [
        migrations.AlterModelTable(name="reactor_unit", table="reactor_unit",),
        migrations.AlterModelTable(name="report_data", table="Report_data",),
    ]
