# Generated by Django 4.2.5 on 2023-09-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("us_nrc", "0025_alter_reactor_unit_table_alter_report_data_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reactor_unit",
            name="ReactorType",
            field=models.IntegerField(max_length=200),
        ),
        migrations.AlterModelTable(name="reactor_unit", table=None,),
        migrations.AlterModelTable(name="report_data", table=None,),
    ]
