# Generated by Django 4.2.5 on 2023-09-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("us_nrc", "0026_alter_reactor_unit_reactortype_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reactor_unit",
            name="ReactorType",
            field=models.CharField(max_length=200),
        ),
    ]
